-- DROP 시퀀스
DROP SEQUENCE GUEST_SEQ;
DROP SEQUENCE SALES_SEQ;
DROP SEQUENCE HAIR_SEQ;
DROP SEQUENCE EVENT_SEQ;
DROP SEQUENCE BOOK_SEQ;



-- CREATE 시퀀스
CREATE SEQUENCE GUEST_SEQ
    START WITH 1
    INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE SALES_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE HAIR_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE EVENT_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;

CREATE SEQUENCE BOOK_SEQ
	START WITH 1
	INCREMENT BY 1
	NOCACHE;


/*
-- 앞으로 써야할 INSERT문

INSERT INTO [TABLE명]
VALUES([시퀀스명].NEXTVAL, .. );

-- 패널에 고객번호, 주문번호, 예약번호가 자동으로 입력되게 그 다음에 써야할 시퀀스 번호를 조회하는 SQL문
SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = '[시퀀스명]';

*/