SELECT S.SALES_NO AS 영업번호 ,TO_CHAR( S.SALES_DAY ,'YYYY-MM-DD')AS 영업일자 ,g.GUEST_NAME AS 고객명,h.HAIR_NAME AS 헤어명  ,E.EVENT_NAME AS 이벤트명 ,S.TOTAL_PRICE AS 가격
FROM SALES s
	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO 
	WHERE TO_CHAR(S.SALES_DAY,'YYYY') BETWEEN 2000 AND 2021
	ORDER BY SALES_NO;

SELECT S.SALES_NO AS 영업번호 ,TO_CHAR( S.SALES_DAY ,'YYYY-MM-DD')AS 영업일자 ,g.GUEST_NAME AS 고객명 ,h.HAIR_NAME AS 헤어명 ,E.EVENT_NAME AS 이벤트명 ,S.TOTAL_PRICE AS 가격
FROM SALES s
	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO 
	WHERE TO_CHAR(S.SALES_DAY,'MM') =  12 ;

INSERT INTO GUEST	
VALUES(1, '이지수', TO_DATE('1900-01-02', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 2, NULL);
INSERT INTO GUEST
VALUES(2, '김대훈', TO_DATE('1900-12-01', 'YYYY-MM-DD'), SYSDATE, '010-4321-8765', 1, NULL);

SELECT * FROM SALES s2 ;

INSERT INTO HAIR VALUES (1,'커트',3000);
INSERT INTO HAIR VALUES (2,'염색',5000);

INSERT INTO EVENT VALUES (1,'생일쿠폰', 0.15);
INSERT INTO EVENT VALUES (2,'1주년', 0.3);

INSERT INTO SALES VALUES (1,TO_DATE('2000-12-01','yyyy-mm-dd'),1,1,1);
INSERT INTO SALES VALUES (2,TO_DATE('2000-12-01','yyyy-mm-dd'),2,2,2);
INSERT INTO SALES VALUES (3,TO_DATE('2000-12-01','yyyy-mm-dd'),1,2,1);
INSERT INTO SALES VALUES (4,TO_DATE('2000-12-01','yyyy-mm-dd'),2,2,1);

INSERT INTO GUEST VALUES(0, '비회원', TO_DATE('1990-02-20', 'YYYY-MM-DD'), SYSDATE, '010-1234-5678', 1, NULL);

INSERT INTO SALES_DETAIL VALUES (1,1,1);
INSERT INTO SALES_DETAIL VALUES (2,1,2);

SELECT * FROM SALES s ;
SELECT * FROM HAIR h ;


SELECT S.SALES_NO AS 영업번호 ,TO_CHAR( S.SALES_DAY ,'YYYY-MM-DD')AS 영업일자 ,g.GUEST_NAME AS 고객명,h.HAIR_NAME AS 헤어명  ,E.EVENT_NAME AS 이벤트명 ,H.PRICE AS 가격
FROM SALES s
	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO 
	WHERE TO_CHAR(S.SALES_DAY,'YYYY') BETWEEN 2000 AND 2021;



SELECT S.SALES_NO AS 영업번호 ,TO_CHAR( S.SALES_DAY ,'YYYY-MM-DD')AS 영업일자 ,g.GUEST_NAME AS 고객명,h.HAIR_NAME AS 헤어명  ,E.EVENT_NAME AS 이벤트명 ,S.TOTAL_PRICE AS 가격
FROM SALES s
	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO 
	WHERE TO_CHAR(S.SALES_DAY,'YYYY') BETWEEN 2000 AND 2021
	ORDER BY SALES_NO;

SELECT TO_CHAR(SALES_DAY, 'YYYY'), COUNT(*)
FROM SALES
	WHERE TO_CHAR(SALES_DAY, 'YYYY') >= 2000 AND TO_CHAR(SALES_DAY, 'YYYY') < 2021;
	GROUP BY TO_CHAR(SALES_DAY, 'YYYY');
--	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
--	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
--	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO 


-- 연도별
SELECT TO_CHAR(SALES_DAY, 'YYYY') YEAR,, SUM(TOTAL_PRICE ) SUM 
FROM SALES s
	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO 
GROUP BY TO_CHAR(SALES_DAY, 'YYYY')
HAVING to_char(sales_day, 'YYYY') BETWEEN 2015 AND 2020;

SELECT S.SALES_NO AS 영업번호 ,TO_CHAR( S.SALES_DAY ,'YYYY-MM-DD')AS 영업일자 ,g.GUEST_NAME AS 고객명 ,h.HAIR_NAME AS 헤어명 ,E.EVENT_NAME AS 이벤트명 ,S.TOTAL_PRICE AS 가격
FROM SALES s
	LEFT OUTER JOIN GUEST g ON S.GUEST_NO = G.GUEST_NO 
	LEFT OUTER JOIN HAIR h  ON S.SALES_NO =  H.HAIR_NO 
	LEFT OUTER JOIN EVENT e ON S.EVENT_NO = E.EVENT_NO
	WHERE TO_CHAR(S.SALES_DAY,'YYYY') BETWEEN 2000 AND 2021;




-- 월별
SELECT TO_CHAR(SALES_DAY, 'MM') YEAR, COUNT(*) COUNT, SUM(TOTAL_PRICE ) SUM 
FROM SALES S
WHERE TO_CHAR(SALES_DAY, 'YYYY') = 2020
GROUP BY TO_CHAR(SALES_DAY, 'MM');




SELECT * FROM sales;

-- Impl에 들어간 거
SELECT TO_CHAR(SALES_DAY, 'YYYY') YEAR, SUM(TOTAL_PRICE ) SUM 
 FROM SALES  GROUP BY TO_CHAR(SALES_DAY, 'YYYY') 
 HAVING to_char(sales_day, 'YYYY') BETWEEN 2015 AND 2020;