SELECT * FROM SALES;

SELECT * FROM SALES WHERE SALES_DAY BETWEEN DATE_ADD(now(),INTERVAL  -1 DAY ) AND now();

SELECT * FROM SALES WHERE SALES_DAY BETWEEN DATE_ADD(NOW(),INTERVAL -1 DAY ) AND NOW();

SELECT * FROM SALES WHERE SALES_DAY > (now() - INTERVAL 7 Day);

SELECT * FROM SALES WHERE SALES_DAY > subdate ;

INSERT INTO SALES VALUES (6,TO_DATE('2020-08-25','yyyy-mm-dd'),2,2,1);

SELECT * FROM SALES WHERE SALES_DAY >= TO_CHAR(SYSDATE-7,'YYYYMMDD');

SELECT * FROM SALES WHERE SALES_DAY BETWEEN TO_DATE('2020-08-24','yyyy-mm-dd') AND TO_DATE('2020-08-26','yyyy-mm-dd');